import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { REGIONS } from '../src/data/regions.js';
import { CORTICAL_IDS } from '../src/brain/parcellation.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (rel) => readFileSync(path.join(root, rel), 'utf8');

// Mirror build.py: drop local imports, hoist-and-drop CDN imports, strip `export `.
// Everything then shares one scope — exactly how it runs in dist/index.html.
const IMPORT_RE = /^\s*import\s+(?:[^'"]*?\s+from\s+)?['"]([^'"]+)['"]\s*;?\s*$/;
function bundle(files) {
  return files.map((f) => read(f).split('\n').map((line) => {
    if (IMPORT_RE.test(line)) return '';
    if (line.startsWith('export ')) return line.slice('export '.length);
    return line;
  }).join('\n')).join('\n');
}

const BRAIN_FILES = ['src/lib/noise.js', 'src/brain/parcellation.js', 'src/brain/geometry.js', 'src/brain/scene.js'];

/** Evaluate the concatenated brain modules with a stub THREE. Loading them must be inert. */
function loadBrainScope() {
  const src = bundle(BRAIN_FILES) +
    '\n;({ regionColor, REGION_COLORS, SUBCORTICAL_SPECS, SUBCORTICAL_IDS, BRAIN, buildBrain, createScene })';
  const sandbox = {
    THREE: new Proxy({}, { get() { throw new Error('THREE was touched at module load time'); } }),
    mergeVertices() { throw new Error('mergeVertices was called at module load time'); },
    OrbitControls: null, EffectComposer: null, RenderPass: null, UnrealBloomPass: null, OutputPass: null,
    window: undefined, document: undefined, performance: undefined,
  };
  return vm.runInNewContext(src, vm.createContext(sandbox), { filename: 'brain-bundle.js' });
}

test('the brain modules have no top-level side effects (they load without THREE or the DOM)', () => {
  const s = loadBrainScope();
  assert.equal(typeof s.buildBrain, 'function');
  assert.equal(typeof s.createScene, 'function');
  assert.equal(typeof s.regionColor, 'function');
});

test('the 3D scene covers exactly the 28 REGIONS ids', () => {
  const s = loadBrainScope();
  const ids = CORTICAL_IDS.concat(s.SUBCORTICAL_IDS);
  assert.equal(new Set(ids).size, ids.length, 'an id is modelled twice');
  const known = REGIONS.map((r) => r.id);
  assert.equal(ids.length, 28, `scene models ${ids.length} regions`);
  assert.deepEqual([...ids].sort(), [...known].sort());
});

test('every region has its own colour, and the colours are distinguishable', () => {
  const s = loadBrainScope();
  const rgb = (hex) => [(hex >> 16) & 255, (hex >> 8) & 255, hex & 255];
  const entries = REGIONS.map((r) => [r.id, s.regionColor(r.id)]);
  for (const [id, c] of entries) {
    assert.ok(Number.isInteger(c) && c >= 0 && c <= 0xffffff, `${id} has no colour`);
    assert.ok(Object.prototype.hasOwnProperty.call(s.REGION_COLORS, id), `${id} missing from REGION_COLORS`);
  }
  let worst = Infinity, worstPair = '';
  for (let i = 0; i < entries.length; i++) {
    for (let j = i + 1; j < entries.length; j++) {
      const a = rgb(entries[i][1]), b = rgb(entries[j][1]);
      const d = Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2]);
      if (d < worst) { worst = d; worstPair = `${entries[i][0]} vs ${entries[j][0]}`; }
    }
  }
  // 28 colours cannot all be far apart; 40 units of RGB distance is about the practical
  // floor for "tell these two apart as an 8px dot". The palette is generated by spreading
  // hues and then maximising this minimum (see REGION_COLORS in geometry.js).
  assert.ok(worst > 40, `colours too close: ${worstPair} (distance ${worst.toFixed(1)})`);
});

test('every discrete structure sits inside the modelled head volume', () => {
  const s = loadBrainScope();
  const lim = { x: s.BRAIN.sx * 1.35, y: s.BRAIN.sy * 1.6, z: s.BRAIN.sz * 1.1 };
  for (const spec of s.SUBCORTICAL_SPECS) {
    for (const part of spec.parts) {
      const pts = part.at ? [part.at] : (part.points || [part.from, part.to]);
      for (const p of pts) {
        assert.ok(Math.abs(p[0]) < lim.x, `${spec.id} x=${p[0]} outside the head`);
        assert.ok(Math.abs(p[1]) < lim.y, `${spec.id} y=${p[1]} outside the head`);
        assert.ok(Math.abs(p[2]) < lim.z, `${spec.id} z=${p[2]} outside the head`);
      }
      if (part.at && spec.mirror) assert.ok(part.at[0] >= 0, `${spec.id} mirrored parts must be authored on the right (+x)`);
    }
  }
});

test('scene.js implements the whole Scene API from CONTRACTS.md', () => {
  const src = read('src/brain/scene.js');
  const members = [
    'THREE', 'renderer', 'camera', 'scene', 'controls', 'regionIds',
    'centroid', 'highlight', 'clearHighlights', 'setLesion', 'clearLesions',
    'flyTo', 'resetView', 'setCortexOpacity', 'setQuality',
    'onPick', 'onHover', 'pulse', 'addOverlay', 'removeOverlay', 'update', 'render',
  ];
  for (const m of members) {
    assert.ok(new RegExp(`(^|[\\s{,])${m}\\s*[(:,]`, 'm').test(src), `Scene API member missing: ${m}`);
  }
  assert.ok(/webglcontextlost/.test(src), 'no WebGL context-loss handler');
  assert.ok(/webgl-lost/.test(src), 'context loss must reveal #webgl-lost');
  assert.ok(/UnrealBloomPass/.test(src) && /EffectComposer/.test(src), 'bloom is not wired');
  assert.ok(/onBeforeCompile/.test(src), 'no shader injection for the highlight glow');
  assert.ok(/setPixelRatio\(Math\.min\(window\.devicePixelRatio \|\| 1, (maxDpr|high \? maxDpr)/.test(src), 'DPR must be capped');
});

test('deep structures are lit, not self-lit, at rest — and still pop when selected', () => {
  const s = loadBrainScope();
  const geo = read('src/brain/geometry.js');
  const scn = read('src/brain/scene.js');
  // The resting glow is the whole depth hierarchy: at 0.20 the structures out-shouted the
  // cortex and the brain read as glowing beads in jelly.
  const rest = +(geo.match(/STRUCTURE_REST_EMISSIVE\s*=\s*([0-9.]+)/) || [])[1];
  assert.ok(rest > 0 && rest <= 0.06, `resting emissive intensity is ${rest}, expected <= 0.06`);
  const gain = +(scn.match(/BRAIN_EMISSIVE_GAIN\s*=\s*([0-9.]+)/) || [])[1];
  assert.ok(gain >= 1.5, `selection ramp is only ${gain} — a selected structure has to be unmistakable`);
  assert.ok(/BRAIN_EMISSIVE_REST \+ BRAIN_EMISSIVE_GAIN \* w/.test(scn), 'the ramp is not wired to the highlight weight');
});

test('the cortex surface is a few large folds, not noise', () => {
  const s = loadBrainScope();
  const geo = read('src/brain/geometry.js');
  // The crumpled look has one cause every time: displacement whose wavelength is close to
  // the vertex spacing. These four numbers are the guard rails against re-introducing it.
  assert.ok(s.BRAIN.foldOctaves <= 2, `${s.BRAIN.foldOctaves} octaves puts detail at the vertex spacing`);
  assert.ok(s.BRAIN.foldFreq <= 2.0, `fold frequency ${s.BRAIN.foldFreq} is too high for readable gyri`);
  assert.equal(s.BRAIN.fineAmp, undefined, 'the fine high-frequency octave is back');
  const depthPct = 100 * s.BRAIN.sulcusDepth / s.BRAIN.meanRadius;
  assert.ok(depthPct >= 2.0 && depthPct <= 3.5, `sulcus depth is ${depthPct.toFixed(1)}% of the radius`);
  assert.ok(s.BRAIN.sylvianDepth > s.BRAIN.sulcusDepth && s.BRAIN.centralDepth > s.BRAIN.sulcusDepth,
    'the two named fissures must be deeper than the anonymous folds');
  // domain warp, and the relaxation pass that removes the icosahedron's own faceting
  assert.ok(s.BRAIN.warpAmp > 0 && s.BRAIN.warpFreq < s.BRAIN.foldFreq, 'the fold field is not domain-warped');
  assert.ok(/function brainSmoothPositions/.test(geo), 'no Laplacian smoothing pass');
  assert.ok(s.BRAIN.smoothPasses >= 2, `only ${s.BRAIN.smoothPasses} smoothing pass(es)`);
  assert.equal((geo.match(/^\s+brainSmoothPositions\(geo,/gm) || []).length, 2,
    'both the hemisphere and the cerebellum have to be relaxed');
  // triangle budget: 20*(detail+1)^2 per hemisphere, and the whole scene must fit in 120k
  const hemiTris = 20 * Math.pow(s.BRAIN.detail + 1, 2);
  assert.ok(2 * hemiTris < 100000, `hemispheres alone are ${2 * hemiTris} triangles`);
});

test('the striatum does not collide with the Atlas accent colour', () => {
  const s = loadBrainScope();
  const accent = parseInt((read('src/modes/atlas.js').match(/accent:\s*0x([0-9a-f]{6})/i) || [])[1], 16);
  assert.ok(Number.isInteger(accent), 'could not find AtlasMode.accent');
  const rgb = (hex) => [(hex >> 16) & 255, (hex >> 8) & 255, hex & 255];
  const d = (a, b) => Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2]);
  // Selecting the striatum tints it WITH the accent, so a base colour near the accent means
  // "selected" and "not selected" look the same.
  const dist = d(rgb(s.regionColor('striatum')), rgb(accent));
  assert.ok(dist > 70, `striatum is only ${dist.toFixed(1)} from the atlas accent`);
});

test('the default camera is a left-lateral three-quarter, and resetView returns to it', () => {
  const src = read('src/brain/scene.js');
  const pos = (src.match(/BRAIN_HOME_POS = \[([^\]]+)\]/) || [])[1].split(',').map(Number);
  const tgt = (src.match(/BRAIN_HOME_TARGET = \[([^\]]+)\]/) || [])[1].split(',').map(Number);
  assert.equal(pos.length, 3); assert.equal(tgt.length, 3);
  // The left hemisphere is the UNMIRRORED one, and the hemisphere is authored with +x
  // lateral — so the left hemisphere lives at +x and the camera has to be there to see its
  // lateral surface (Broca and Wernicke exist nowhere else). These two facts have to agree.
  assert.ok(/if \(side === 'right'\) mesh\.scale\.x = -1;/.test(read('src/brain/geometry.js')),
    'the RIGHT hemisphere is the mirrored one: +x is the subject\'s left');
  assert.ok(pos[0] > 0, 'the camera must sit on the LEFT hemisphere side (+x)');
  assert.ok(pos[1] > 0, 'the default view looks slightly DOWN at the brain');
  assert.ok(pos[2] > 0, 'the frontal pole must face the camera side, so the pose is a three-quarter not a profile');
  // ~15 degrees above the horizontal: enough to see the superior surface, not a top-down.
  const elev = Math.atan2(pos[1] - tgt[1], Math.hypot(pos[0] - tgt[0], pos[2] - tgt[2])) * 180 / Math.PI;
  assert.ok(elev > 10 && elev < 22, `camera elevation is ${elev.toFixed(1)} degrees`);
  const dist = Math.hypot(pos[0] - tgt[0], pos[1] - tgt[1], pos[2] - tgt[2]);
  assert.ok(dist > 3.0 && dist < 5.0, `home distance ${dist.toFixed(2)} will not frame the whole brain`);
  // Panned off the midline so the brain sits in the gap between the side panel and the Explain
  // card. `tgt[0] < 0` used to stand in for this, but that only held while the pan went screen-LEFT;
  // since round 4 the camera sits further back and the pan goes the other way, to pull the
  // cerebellum out from under the Explain card. Check the pan itself instead of its x component:
  // the offset of the target along the camera's screen-right axis must be positive and non-trivial.
  const fwd = [tgt[0] - pos[0], tgt[1] - pos[1], tgt[2] - pos[2]];
  const rLen = Math.hypot(-fwd[2], fwd[0]);
  const right = [-fwd[2] / rLen, 0, fwd[0] / rLen];
  const pan = tgt[0] * right[0] + tgt[2] * right[2];
  assert.ok(pan > 0.03, `the rig is panned by ${pan.toFixed(3)}: the brain will drift under the Explain card`);
  // resetView must fly to the SAME constants, not to a second hard-coded pose
  const reset = src.slice(src.indexOf('resetView()'), src.indexOf('resetView()') + 400);
  assert.ok(/BRAIN_HOME_POS\[0\]/.test(reset) && /BRAIN_HOME_TARGET\[0\]/.test(reset), 'resetView does not use the home constants');
});

test('the cortex is the primary object: cool, semi-matte, front faces, one blended skin', () => {
  const geo = read('src/brain/geometry.js');
  const body = read('src/body.html');
  const sceneDefault = +(read('src/brain/scene.js').match(/setCortexOpacity\(([0-9.]+)\)/) || [])[1];
  const sliderDefault = +(body.match(/id="cortex-opacity"[^>]*value="([0-9.]+)"/) || [])[1];
  assert.equal(sceneDefault, sliderDefault, 'scene default and the #cortex-opacity slider disagree');
  assert.equal(sceneDefault, 0.63, `a ${sceneDefault} shell is not the agreed default`);
  const mat = geo.slice(geo.indexOf('const cortexMaterial'), geo.indexOf('const hemispheres'));
  const rough = +(mat.match(/roughness:\s*([0-9.]+)/) || [])[1];
  assert.ok(rough >= 0.45 && rough <= 0.65, `cortex roughness ${rough}: too glossy hides the gyri, too matte kills the sheen`);
  // Cool and desaturated. A warm shell reads as beige wax against this dark blue UI, and
  // that is exactly what rounds 1-2 produced.
  const hex = parseInt((mat.match(/color:\s*0x([0-9a-f]{6})/i) || [])[1], 16);
  const r = (hex >> 16) & 255, g = (hex >> 8) & 255, b = hex & 255;
  assert.ok(b > r, `cortex colour #${hex.toString(16)} is warm (r ${r} >= b ${b})`);
  assert.ok(Math.max(r, g, b) - Math.min(r, g, b) < 60, 'the cortex must stay desaturated');
  assert.ok(/side: THREE\.FrontSide/.test(mat), 'the shell must render front faces only');
  assert.ok(/depthWrite: false/.test(mat), 'a translucent shell that writes depth hides the structures behind it');
  assert.ok(/forceSinglePass: true/.test(mat), 'the shell must be a single blended skin');
  assert.ok(!/transmission:\s*[1-9.]/.test(mat), 'no transmission: it costs a second scene render and looks like glass');
});

test('the backdrop is a soft vignette with a ground glow, not a flat fill', () => {
  const src = read('src/brain/scene.js');
  // A translucent grey object on a flat near-black has no edge and no ground; the whole
  // image reads as haze. The centre is the navy the brain sits against, the corners keep the
  // old clear colour.
  const stops = (src.match(/const BRAIN_BG_STOPS = \[([\s\S]*?)\];/) || [])[1] || '';
  const cols = stops.match(/#[0-9a-f]{6}/gi) || [];
  assert.ok(cols.length >= 3, `only ${cols.length} gradient stops — that is a flat fill, not a vignette`);
  assert.ok(cols.includes('#121523'), 'the vignette centre must be the agreed deep navy #121523');
  assert.equal(cols[cols.length - 1], '#0a0b0f', 'the vignette must fade to #0a0b0f at the corners');
  assert.ok(/scene\.background = backdrop/.test(src), 'the gradient is never assigned to scene.background');
  assert.ok(/CanvasTexture/.test(src) && /colorSpace = THREE\.SRGBColorSpace/.test(src),
    'a canvas-authored background must be tagged sRGB or it renders washed out');
  // ground glow: additive, dim, and under the brain
  assert.ok(/AdditiveBlending/.test(src) && /groundGlow/.test(src), 'no ground glow');
  const glowOpacity = +(src.match(/BRAIN_GLOW_OPACITY = ([0-9.]+)/) || [])[1];
  assert.ok(glowOpacity > 0 && glowOpacity <= 0.25,
    `ground glow opacity ${glowOpacity}: above ~0.25 it shows THROUGH the shell and tints the brain`);
  const glowY = +(src.match(/groundGlow\.position\.set\(0, (-[0-9.]+)/) || [])[1];
  assert.ok(glowY < -1.0, `the glow sits at y=${glowY}, which is not under the brain`);
});

test('deep structures recede with depth, and come back when you need them', () => {
  const src = read('src/brain/scene.js');
  const cue = +(src.match(/BRAIN_DEPTH_CUE = ([0-9.]+)/) || [])[1];
  assert.ok(cue > 0.2 && cue <= 0.7, `depth cue ${cue}: too little does nothing, too much loses the far structures`);
  // depth is measured along the VIEW axis, so it follows the camera instead of being baked
  assert.ok(/camera\.getWorldDirection\(tmpFwd\)/.test(src) && /tmpVec\.dot\(tmpFwd\)/.test(src),
    'the depth cue must be camera-relative, not a fixed per-structure constant');
  const line = (src.match(/const cue = BRAIN_DEPTH_CUE \* [^;]+;/) || [])[0] || '';
  assert.ok(/\(1 - w\)/.test(line), 'a selected or hovered structure must not be dimmed by the depth cue');
  assert.ok(/veil/.test(line) && /cortexMaterial\.opacity/.test(src),
    'the depth cue must fade out as the cortex slider opens — there is nothing left to be behind');
  assert.ok(/depthDirty = true;\s*\/\/ with the shell open/.test(src),
    'moving the cortex slider must invalidate the depth cue');
});

test('the view drifts when it is left alone and stops the moment you touch it', () => {
  const src = read('src/brain/scene.js');
  assert.ok(/setIdleRotate\(on\)/.test(src), 'scene.setIdleRotate is missing from the API');
  assert.ok(/let idleRotate = true;/.test(src), 'the idle drift must be on by default');
  const delay = +(src.match(/BRAIN_IDLE_DELAY = ([0-9.]+)/) || [])[1];
  const speed = (src.match(/BRAIN_IDLE_SPEED = ([0-9.]+) \* Math\.PI \/ 180/) || [])[1];
  assert.ok(delay >= 3 && delay <= 6, `idle delay ${delay}s is not the agreed ~4 s`);
  assert.equal(+speed, 4, `idle speed is ${speed} deg/s, not the agreed 4`);
  // every pointer route has to reset the timer, or the brain rotates under the cursor
  for (const ev of ['pointerdown', 'pointermove', 'wheel']) {
    assert.ok(new RegExp(`addEventListener\\('${ev}'[^\n]*brainNoteInteraction`).test(src),
      `${ev} does not stop the idle drift`);
  }
  assert.ok(/controls\.addEventListener\('start', \(\) => \{ fly = null; brainNoteInteraction\(\); \}\)/.test(src),
    'an orbit drag does not stop the idle drift');
  assert.ok(/if \(idleRotate && !fly && !pulses\.length/.test(src),
    'the drift must be suspended while a flight or a pulse is running');
  // the camera orbits; the brain group must never be rotated (centroids are cached in world space)
  assert.ok(!/brain\.group\.rotation/.test(src), 'rotating the brain group invalidates every cached centroid');
});

test('the selected region breathes, and only the selected one', () => {
  const src = read('src/brain/scene.js');
  const amp = +(src.match(/BRAIN_PULSE_AMP = ([0-9.]+)/) || [])[1];
  assert.ok(amp > 0.04 && amp <= 0.15, `pulse amplitude ${amp} is not the agreed +/-10%`);
  assert.ok(/uniforms\.uHiPulse\.value = pulsePhase/.test(src), 'the cortex pulse uniform is never driven');
  assert.ok(/smoothstep\(0\.55, 1\.0, bHi\)/.test(src),
    'the pulse must be gated on the highlight weight so a HOVERED patch does not flicker');
  assert.ok(/float bHi = vHi \* vTint\.a;/.test(src),
    'the selection glow must be feathered like the resting tint, or it reads as a jagged sticker');
  assert.ok(/pulsePhase \* brainStep01\(0\.55, 1\.0, w\)/.test(src), 'deep structures do not share the breath');
});

test('quality Low keeps the vignette, the baked shade and the depth cue — it only drops bloom', () => {
  const src = read('src/brain/scene.js');
  const q = src.slice(src.indexOf('function brainApplyQuality'), src.indexOf('/* ------'
    , src.indexOf('function brainApplyQuality')));
  assert.ok(/bloomOn = !!high/.test(q) && /setPixelRatio/.test(q) && /clearcoat/.test(q),
    'brainApplyQuality should still gate bloom, pixel density and the clearcoat sheen');
  for (const forbidden of ['background', 'groundGlow', 'uSulcusAO', 'BRAIN_DEPTH_CUE', 'idleRotate']) {
    assert.ok(!q.includes(forbidden), `quality Low must not turn off ${forbidden}`);
  }
});

test('the sulcal shade is what makes the folds readable through a translucent shell', () => {
  const src = read('src/brain/scene.js');
  const ao = +(src.match(/uSulcusAO = \{ value: ([0-9.]+) \}/) || [])[1];
  assert.ok(ao >= 0.85, `groove darkening is only ${ao}: the folds go back to being a haze`);
  // crowns lifted as well as floors dropped, and a contrast curve on the relaxed attribute
  assert.ok(/float bSul = smoothstep\([0-9.]+, [0-9.]+, vSul\);/.test(src), 'the sulcus attribute has no contrast curve');
  const lift = +(src.match(/float bAo = mix\(([0-9.]+), 1\.0 - uSulcusAO/) || [])[1];
  assert.ok(lift > 1.0 && lift < 1.15, `crown lift ${lift}: above ~1.15 the gyri clip into bright worms`);
  // a warm crown against a cool groove floor: the tone ramp is what reads as relief
  const tone = src.match(/vec3 bTone = mix\(vec3\(([0-9.]+), [0-9.]+, ([0-9.]+)\), vec3\(([0-9.]+), [0-9.]+, ([0-9.]+)\)/);
  assert.ok(tone, 'no crown-to-groove tone ramp');
  assert.ok(+tone[1] > +tone[2], 'crowns must be the WARM end of the ramp (r > b)');
  assert.ok(+tone[4] > +tone[3], 'groove floors must be the COOL end of the ramp (b > r)');
  // grooves are painted more solidly, not made thinner: see the comment in scene.js
  assert.ok(/diffuseColor\.a = clamp\(diffuseColor\.a \* \(1\.0 \+ 0\.[0-9]+ \* bSul\)/.test(src),
    'grooves must be MORE opaque than crowns, otherwise the fold pattern reads as haze');
});

test('a lost WebGL context rebuilds the post-processing chain instead of reusing it', () => {
  const src = read('src/brain/scene.js');
  assert.ok(/function brainDisposeComposer/.test(src), 'no composer teardown');
  const lost = src.slice(src.indexOf("addEventListener('webglcontextlost'"), src.indexOf("addEventListener('webglcontextrestored'"));
  assert.ok(/brainDisposeComposer\(\)/.test(lost), 'the composer is not thrown away when the context dies');
  const restored = src.slice(src.indexOf("addEventListener('webglcontextrestored'"));
  assert.ok(/api\.setQuality\(quality\)/.test(restored.slice(0, 500)), 'the chain is not rebuilt after restore');
  assert.ok(/renderTarget1 = null/.test(src) && /renderTarget2 = null/.test(src), 'render targets are not nulled');
});

test('the brain code adds no new CDN hosts', () => {
  for (const f of BRAIN_FILES) {
    const hosts = read(f).match(/https?:\/\/[^\s'"`)]+/g) || [];
    for (const h of hosts) assert.fail(`${f} references an external URL: ${h}`);
    for (const spec of read(f).match(/from\s+['"]([^'".][^'"]*)['"]/g) || []) {
      assert.ok(/'three'|"three"|three\/addons\//.test(spec), `${f}: unexpected bare import ${spec}`);
    }
  }
});
